### PR TITLE
feat: add support for token/channel option

### LINKED ISSUE #73: Configuration for Slack channel
It would be great to have ability to configure Slack channel via plugin option and environment variable

### PR DESCRIPTION
**Pull request by SimeonC**
Supporting alternative to the webhook url that makes use of a channel name and oauth token

fix #73

### CODE REVIEW

**Comment by juliuscc** [comment]
Could you add some documentation for the new configuration settings? 😁

**Comment by SimeonC** [comment]
I completely forgot!! Will update shortly.

**Comment by SimeonC** [comment]
@juliuscc Have updated.

**Review by juliuscc — APPROVED** [review]

**Comment by juliuscc** [comment]
This looks great to me! 👍 

Thanks for cleaning up the docs in general as well!

**Pull request merged**
