### PR TITLE
BREAKING CHANGE: Bump dependencies

### PR DESCRIPTION
**Pull request by BeyondEvil**
I think it's good to do development on the latest version of Semantic Release.

Fixes: #56 
Closes: #51

### CODE REVIEW

**Comment by juliuscc** [comment]
Yes I agree. Do you know what the breaking changes are and if it affects us?

**Comment by BeyondEvil** [comment]
> Yes I agree. Do you know what the breaking changes are and if it affects us?

As far as I can tell, the only thing is the requirement of node >= 10.13. Read more [here](https://github.com/semantic-release/semantic-release/releases/tag/v16.0.0) @juliuscc

**Comment by juliuscc** [comment]
Could we do this together with bumping the version for slackify-markdown? And also updating the engines.node field in package.json?

**Comment by juliuscc** [comment]
I checked our CircleCI-config and we are running our tests on node v10, so I think we are fine in that aspect

**Comment by BeyondEvil** [comment]
Sure, I'll try to sort it today. 👍

**Comment by BeyondEvil** [comment]
Ready (I think) @juliuscc

**Comment by juliuscc** [comment]
Thanks! Great work 😁

**Pull request merged**
