### PR TITLE
BREAKING CHANGE: Send slack message using multiple sections

### PR DESCRIPTION
**Pull request by BeyondEvil**
Instead of truncating release notes etc. before sending to slack,
we can split the message into multiple chunks that adhere to the
slack message-size limitation. Each chunk can then be added as its
own section before sending.

Not sure if it's really breaking, but there are two changes that might be significant. For one, it's not truncating anymore. But also, it will now create a proper slack message (Block Kit style) when overriding the `onSuccessTemplate`.

Storytime: So I was working on this thing for work where I needed to send a slack message from an AWS Lambda function. By accident, I discovered that the 3000 character limit only seems to apply _per_ section. 🤷‍♂

### CODE REVIEW

**Comment by BeyondEvil** [comment]
Another approach, if we don't want to make a major (breaking) release, is to keep the truncation and "hide" the new functionality behind a config setting. Say `sendFullMessage`. 🤔 💡

**Comment by BeyondEvil** [comment]
Would be nice to get your input on this as well @AndrewLeedham 👍 

Specifically note that I've changed so that when providing your own ´onSuccessTemplate´, this will be "sectionized".

**Comment by AndrewLeedham** [comment]
Would this not limit the `onSuccessTemplate` to be a single block? Since you are accessing `'text'` and assuming it is at the top level.

**Comment by BeyondEvil** [comment]
> Would this not limit the `onSuccessTemplate` to be a single block? Since you are accessing `'text'` and assuming it is at the top level.

So, there are two parts to the payload of a slack message.

`blocks` and `text`

Afaict, the `text` is a fallback of sorts.

So when running this:

```javascript
const [firstLine, ...restLines] = templatedMessage['text'].split('\n')
``` 
I later set _both_ `text` and the first `section` of `blocks` to the first line (all text until the first new line).

```javascript
  const messageBlocks = [
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: slackBaseText
      }
    }
  ]
```

Does that make sense?

It's not perfect, but a best effort to create that "fallback" `text`.

@AndrewLeedham

**Comment by BeyondEvil** [comment]
Oh, wait. I see now. I made the (incorrect) assumption that `template` will always spit out a string. 🙈 

So, the chunking is valid if you're not providing a template. But in the template case, this is perhaps a lot more complex...

**Comment by AndrewLeedham** [comment]
Yeah that is essentially the conclusion we came to here: https://github.com/juliuscc/semantic-release-slack-bot/issues/26#issuecomment-570051131

**Comment by BeyondEvil** [comment]
Ok, so let's take a step back.

## Problem Statement

Truncating release notes risks cutting away the interesting parts (depending on what convention you use).

For example, we use `eslint`, which means that for even just moderate sized release notes, only the commits that doesn't trigger a release are shown (`Chore` in the case of `eslint`).

Since our release notes are used by sales, support and marketing to communicate to our customers, it's quite important that they can actually see what was released without having to venture into repos (which they probably don't have access to).

## Ideas for solutions

The approach in this PR when _not_ providing a template (e.g. the default configuration) works and should cover most, if not all, scenarios.

The challenge is to handle the situation when a template _is_ provided.

Looking at they keywords available to the template, it's only really `$release_notes` that can ever be so large that it will require handling of some form (truncating, chunking, whatever).

We also know that the template has to follow set rules (the slack messaging format).

### Parsing the template
One approach would be to simply extend the parsing of the template and separate out the release notes and handle them separately. Given the predefined rule set, this should not be (famous last words) to complex to handle. It might however be quite an undertaking due to the extent of the slack messaging format.

### Handle release notes as a special case
By adding a `release_notes` key to the `onSuccessTemplate` object we circumvent all the logic in the "Parsing the template" and can more easily chunkify and sectionize it.


Thoughts? @AndrewLeedham @juliuscc @hannesrabo

**Comment by AndrewLeedham** [comment]
I agree that for most common use-cases people are likely not using `onSuccessTemplate`, and even where it is used I would imagine people are likely to just replicate the existing format with minor tweaks. I do think however still allowing users to specify whatever payload they want is powerful and should not be lost, providing those tools will likely account for edge cases.

Could we perhaps provide the `onSuccessTemplate` format with the ability to chunkify the release notes if necessary, perhaps using something like lodash template or handlebars where we can pass that behaviour as a function/helper.

**Comment by juliuscc** [comment]
> By adding a release_notes key to the onSuccessTemplate object we circumvent all the logic in the "Parsing the template" and can more easily chunkify and sectionize it.

Does this mean an actual key to the object? If it is not, and meant to be a part of a string somewhere I think it can be too difficult.

I *think* it is an impossible problem to figure out how to partition any kind of slack message. There are infinite possibilities in how they are structured. Maybe I am wrong. Do you have any good ideas of where to start? I am a bit confused by the templating, and maybe the structure is not that difficult.

I have a couple of suggestions, and none of them are optimal. Please add to this list:

1. If the template object is only an object with `text`, do the chunkification
2. Add a configuration option that 'explains where to look' in the object for release notes.
3. Introduce another configuration option that is used *instead* of the template. This would be only a string and semantic-slack-release-bot has full responsibility for how to section it.
4. Let the users provide a custom function to generate the message.

As I understand it the largest issue with a template is that it's impossible to create a template with an optional number of blocks/sections, and also to divide one variable over multiple blocks/sections. Is this correct?

**Comment by AndrewLeedham** [comment]
I think option 4 somewhat describes what I was getting at with lodash templates or handlebars. But instead of a function it is a template, it would work exactly the same as it does now, but instead of the user just being able to add keywords that get swapped out for values, they could have logic in the form of loops ifs etc, and we could provide the chunking behaviour for release notes. The chunking behaviour could just return it as an array of strings, so the user can decide how to format each item into blocks or otherwise.

I am not at my computer r/n, but I will write something up with some examples of how this might work later when I am :)

**Comment by BeyondEvil** [comment]
> > By adding a release_notes key to the onSuccessTemplate object we circumvent all the logic in the "Parsing the template" and can more easily chunkify and sectionize it.
> 
> Does this mean an actual key to the object? If it is not, and meant to be a part of a string somewhere I think it can be too difficult.

I meant as a key to the object, but I realized that would break the current "contract" where we say that the `onSuccessTemplate` should be a valid slack object. Of course, we can handle that in the implementation. But still.

> I _think_ it is an impossible problem to figure out how to partition any kind of slack message. There are infinite possibilities in how they are structured. Maybe I am wrong. Do you have any good ideas of where to start? I am a bit confused by the templating, and maybe the structure is not that difficult.

Yeah, I have been looking into it a bit more. And the slack formatting is extremely powerful, which is pretty cool and great, but makes solving this "inline" quite complex.

We can probably do a half decent job if we make loads of assumptions. But I think there's a way of solving this without having to make all those assumptions.

> I have a couple of suggestions, and none of them are optimal. Please add to this list:
> 
>     1. If the template object is only an object with `text`, do the chunkification

Yes, that's basically the current solution.

>     2. Add a configuration option that 'explains where to look' in the object for release notes.

Doable, but would require the user to put a [`block_id`](https://api.slack.com/reference/block-kit/blocks) in the object so we know which of the blocks that contain the release notes. Then it would be easy to replace that block with several blocks of the same type after chunkifying the release notes. 

>     3. Introduce another configuration option that is used _instead_ of the template. This would be only a string and semantic-slack-release-bot has full responsibility for how to section it.

Sounds to me like 1.

>     4. Let the users provide a custom function to generate the message.

Yes, this would likely give the most flexibility, but at the cost of complex implementation. The question is if we support 1 and 2, how often would a user need this? 

> As I understand it the largest issue with a template is that it's impossible to create a template with an optional number of blocks/sections, and also to divide one variable over multiple blocks/sections. Is this correct?

With the current implementation, yes.

**Comment by juliuscc** [comment]
What I meant with option 3 is that we would keep the existing functionality, so that users can create whatever complex slack messages they want. And that we _also_ provide this simpler templating functionality as another configuration option. So we say "Either you get all the flexibility in the world, and you are by your own. Or you get to be handheld by us and only create very simple templates, where we can make many assumptions."

The important thing is that we keep both.

We could also have that if they only give a string as a template we do chunkification, and otherwise not.

**Comment by juliuscc** [comment]
Option 4 is slightly difficult as you can't give a function in a json file or env-variables. They are the only current configuration options.

**Comment by BeyondEvil** [comment]
> What I meant with option 3 is that we would keep the existing functionality, so that users can create whatever complex slack messages they want. And that we _also_ provide this simpler templating functionality as another configuration option. So we say "Either you get all the flexibility in the world, and you are by your own. Or you get to be handheld by us and only create very simple templates, where we can make many assumptions."
> 
> The important thing is that we keep both.
> 
> We could also have that if they only give a string as a template we do chunkification, and otherwise not.

Maybe we misunderstand each other, but I think that is what we would have by adding just an if-statement basically.

If the `onSuccessTemplate` only has one key and that key is `text`, then the user has already told us that it's a simple string that we can chunkify.

If the `onSuccessTemplate` is more complex than the above - we don't do anything other than truncate the release notes. The rest of the message structure is up to the user.

> Option 4 is slightly difficult as you can't give a function in a json file or env-variables. They are the only current configuration options.

I don't think that's correct. You can have the configuration as [.js](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#configuration-file).

I should now, because we use that. 😄

**Comment by AndrewLeedham** [comment]
I like the idea of 'tiered handholding' for lack of a better name. Allowing for a function for advanced use-cases makes a lot of sense to me, [we also use JS config files](https://github.com/xeroxinteractive/config/blob/master/packages/xerox-semantic-release-config/npm.js) and do some manual release_note stuff in an internal project.

> If the onSuccessTemplate only has one key and that key is text, then the user has already told us that it's a simple string that we can chunkify.

Does it even need to be an object? Could they just provide a string, and do some basic value replacement like we do now, and chunkify as necessary?

> If the onSuccessTemplate is more complex than the above - we don't do anything other than truncate the release notes. The rest of the message structure is up to the user.

I think this will lead to the main breaking change, as people will be forced to adopt the new blocks syntax, as release notes will have to be added via blocks. So configurations like mine linked above that use the old `attachements` syntax will break.

**Comment by BeyondEvil** [comment]
> I like the idea of 'tiered handholding' for lack of a better name. Allowing for a function for advanced use-cases makes a lot of sense to me, [we also use JS config files](https://github.com/xeroxinteractive/config/blob/master/packages/xerox-semantic-release-config/npm.js) and do some manual release_note stuff in an internal project.

Agreed, then it's up to the user to decide how much they want to invest into a specific configuration.

> Does it even need to be an object? Could they just provide a string, and do some basic value replacement like we do now, and chunkify as necessary?

I mean, it already is. And I don't see any benefit of changing that. With the current PR that's the behavior. It will handle the input (effectively being a string) including value replacement and chunkification (lol).

> I think this will lead to the main breaking change, as people will be forced to adopt the new blocks syntax, as release notes will have to be added via blocks. So configurations like mine linked above that use the old `attachements` syntax will break.

There must be a misunderstanding here, because that is the current behavior (that is, _not_ the behavior of this PR). You can provide whatever structure you want (as long as it's slack compliant) and we already truncate the release notes (which you don't use in the linked config).

**Comment by AndrewLeedham** [comment]
> I mean, it already is. And I don't see any benefit of changing that. With this PR that's the behavior. It will handle the input (effectively being a string) including value replacement and chunkification (lol).

In my head simplifying the API to `"onSuccessTemplate": "Updates to $package_name has been released to *Stage*!\n\n$release_notes"` meant we could simply do `typeof onSuccessTempate === 'string'` but in hindsight the text field seems like a better user experience as it mimicks the actual payload being send to slack, and is simple enough to check for.

> There must be a misunderstanding here, because that is the current behavior (that is, not the behavior of this PR). You can provide whatever structure you want (as long as it's slack compliant) and we already truncate the release notes (which you don't use in the linked config).

Yeah think this was a misunderstanding, I was thinking the user could provide a payload like:
```jsonc
"onSuccessTemplate": {
  "text": "Updates to $package_name has been released to *Stage*!",
  "blocks": [
    {
        "type": "input"
        // etc.
    }
  ]
}
```
then perhaps there would be an `includeReleaseNotes` option that would concat the chunked release notes onto blocks.

I am not 100% sure what `block_id` is for. From the slack docs it seems it identifies a unique block for referencing. But you seem to be using it here to identify something should be chunked?

## BYOF (Bring Your Own Function)
This behaviour could be fairly simple, the user could just provide a function that takes an object of the values we currently pass to a template. For example:

```javascript
module.exports = {
  // ...
  onSuccessTemplate: function(options) {
    return {
      text: `Updates to ${options.package_name} has been released to *Stage*!`
      // Whatever custom stuff the user wants to do.
    }
  }
  // ...
}
```
We could also export the chunking behaviour, so a user could import it:
```javascript
// Not sure if semantic release will be happy if we export it at the top-level.
// But this is just to illustrate the point.
const { chunkifyText } = require('semantic-release-slack-bot');
module.exports = {
  // ...
  onSuccessTemplate: function(options) {
    return {
      text: `Updates to ${options.package_name} has been released to *Stage*!`
      blocks: chunkifyText(options.release_notes).map(function(chunk) {
        return {
          type: 'section',
          text: {
            type: 'mrkdwn',
            text: chunk
          }
        }
      })
    }
  }
  // ...
}
```

I don't think I mentioned this yesterday but I did some more thinking about lodash templates/handlebars, and realised that they are built for html templates and would not really work here. There are a few json templating languages but they all seem a bit convoluted, and would require the user learning something new. The idea of providing a function seems like the best approach as users will likely already be familiar with JS and it will allow them to import whatever tools they want to use.

**Comment by BeyondEvil** [comment]
> I am not 100% sure what block_id is for. From the slack docs it seems it identifies a unique block for referencing. But you seem to be using it here to identify something should be chunked?

Yes, that's the original intent of the `block_id` and we would sort of re-purpose the use of it to identify a block that needs chunkification. But after giving it some more thought, I think that's an anti-pattern.

Probably better to just introduce a `chunkify` boolean to mark a block that needs it (doesn't have to be just for release notes, but that's the most probable use-case).

If I implement the above, would you be willing to implement the BYOF part? It's a little bit out of my comfort zone. 😊 @AndrewLeedham

**Comment by AndrewLeedham** [comment]
> Yes, that's the original intent of the block_id and we would sort of re-purpose the use of it to identify a block that needs chunkification. But after giving it some more thought, I think that's an anti-pattern.

I see, think that is what confused me. `chunkify` boolean sounds good. Perhaps just `chunk` conveys the meaning?

> If I implement the above, would you be willing to implement the BYOF part? It's a little bit out of my comfort zone. 😊

Can do, that can come as a separate PR. This seems like it would be a non-breaking change which just adds to the current functionality.

**Comment by AndrewLeedham** [comment]
It is probably worth noting that the payload is limited to 50 blocks, so we will need to truncate if splitting the release_notes yields more than 50 blocks. Meaning the total character limit will now be 50 * 3000 = 150,000.

https://api.slack.com/reference/block-kit/blocks

**Comment by BeyondEvil** [comment]
> It is probably worth noting that the payload is limited to 50 blocks, so we will need to truncate if splitting the release_notes yields more than 50 blocks. Meaning the total character limit will now be 50 * 3000 = 150,000.
> 
> https://api.slack.com/reference/block-kit/blocks

Here's my suggestion on how to handle it:

We keep a counter and if that hits 50, we skip the chunking and and just truncate instead. We'll also throw a warning about why. This should be an extremely unlikely event.

Due to how object referencing works in JS, I need to create a new block list anyway, so the above is pretty easy to achieve.

**Comment by AndrewLeedham** [comment]
> We keep a counter and if that hits 50, we skip the chunking and and just truncate instead. We'll also throw a warning about why. This should be an extremely unlikely event.

Would it not be better to just cap the blocks at 50, then we send as much information as possible?

**Comment by BeyondEvil** [comment]
> Would it not be better to just cap the blocks at 50, then we send as much information as possible?

The problem is that the block(s) that need chunking can be in the middle of the list. So if we do it that way, we risk ending up cutting away any "footer" blocks/section.

Example:

Let's say the `onSuccessTemplate` input looks like this:

```javascript
blocks = [
  {
    type: 'section',
    text: {
      type: 'mrkdwn',
      text: 'header'
    }
  },
  {
    chunk: true,
    type: 'section',
    text: {
      type: 'mrkdwn',
      text: 'long release notest'
    }
  },
  {
    type: 'section',
    text: {
      type: 'mrkdwn',
      text: 'footer'
    }
  }
]
```


Then we starting chunking and hit the 50 limit and cut it, and we end up with something like this:

```javascript
blocks = [
  { // block 1
    type: 'section',
    text: {
      type: 'mrkdwn',
      text: 'header'
    }
  },
  { // block 2
    type: 'section',
    text: {
      type: 'mrkdwn',
      text: 'chunk 1'
    }
  },
  .
  .
  .
  { // block 50
    type: 'section',
    text: {
      type: 'mrkdwn',
      text: 'chunk 49'
    }
  }
]
```

No "footer" block.

Is it solveable? Sure, is the implementation complexity worth? Probably not. Especially considering we already have an acceptable fallback -> just truncate the release notes.

**Comment by AndrewLeedham** [comment]
Can we not just do something along the lines of 
```javascript
if (onSuccessTemplate.blocks.length - 1 + chunked.length > 50) {
  chunked = chunked.slice(0, 50 - onSuccessTemplate.blocks.length - 1);
}
```
So we just make sure that the length of chunked blocks + the template blocks do not exceed 50. `-1` accounts for the original block that we are duplicating.

**Comment by BeyondEvil** [comment]
> Can we not just do something along the lines of
> 
> ```js
> if (onSuccessTemplate.blocks.length - 1 + chunked.length > 50) {
>   chunked = chunked.slice(0, 50 - onSuccessTemplate.blocks.length - 1);
> }
> ```
> 
> So we just make sure that the length of chunked blocks + the template blocks do not exceed 50. `-1` accounts for the original block that we are duplicating.

Maybe that solves it. 🤔 Slice is a neat trick.

I'll see if and how it would fit with the rest of my solution. 👍

**Comment by BeyondEvil** [comment]
Sorry for sort of dropping the ball on this.

I had to have some back surgery which caused some issue etc...

I _will_ continue to work on this. I just can't say when.

Happy to relinquish to someone else if they really feel up to it, tho.

**Comment by juliuscc** [comment]
I hope you have a good recovery!

For me, there is no rush to release this. I would rather that it gets the time it needs to come out good, and of course, there is no reason for anyone to push through health issues for an open-source package. I am currently finishing my master thesis so I am very occupied with that.

If nothing has happened by mid-June, I could take a look at it.

**Comment by BeyondEvil** [comment]
@juliuscc @AndrewLeedham 

I'm finally back. Sorry it took so long!

I've pushed what I had worked on back then for record-keeping purposes.

The more I've thought about this, the more I've sort of realized that the sane approach is to basically have two modes.

Basic and advanced.

Basic is what we provide, which is basically this:

- If no `onSucessTemplate` we'll truncate based on the `unsafeMaxLength` option.
    - If `unsafeMaxLength` is turned off (set to '0') we'll chunkify the release notes (adhering to the 50 blocks limit).

Advanced mode:
- If you provide an `onSucessTemplate` we'll again truncate based on the `unsafeMaxLength` option, but this time we make no attempts at "sectionizing" the input. The user bares the full responsible to sanitize the input. We will however expose the chunkify-function so that the user can do as they please.

So I'm going to provide two PRs. One to enable turning off truncation (unsafeMaxLength = 0) and one for the chunikification.

**Comment by juliuscc** [comment]
Great having you back! I have also been off for a while 😅

My master thesis took longer than expected and I had to finish it at the same time as doing my summer internship 😅

**Comment by juliuscc** [comment]
Is this PR redundant or does it add something other than the other ones?

**Comment by BeyondEvil** [comment]
> Is this PR redundant or does it add something other than the other ones?

I wouldn't call it redundant, but it won't get any love from me as I'm not smart enough to solve the complexity of trying to figure out this automatically for users. 😂 

We can probably close it and if someone more [smrt](https://www.youtube.com/watch?v=wv4eTE0aUiQ) feels like taking a stab at it they can re-open the PR.

**Pull request closed without merging**
