### PR TITLE
Bump slackify-markdown from 3.1.0 to 4.3.0

### PR DESCRIPTION
**Pull request by ahermant**
There is an high vulnerability with trim<0.0.3 which is a dependency of slackify-markdown

### CODE REVIEW

**Comment by juliuscc** [comment]
Thanks for your PR! 👍 

I couldn't easily found what breaking change happened when slackify-markdown got bumped to 4.x.x. Do you know what the breaking change is and if it affects us?

**Comment by ahermant** [comment]
You are welcome !
I cannot see any breaking change either from 3.1.0 to 4.0.0.
I did some tests with slackify-markdown 4.3.0 and could not see any issue.
I'll check with the author of slackify-markdown to be sure we are not
missing something.

**Comment by ahermant** [comment]
I just had the confirmation from slackify-markdown that there should be no breaking change from 3.1.0 to 4.0.0:
https://github.com/jsarafajr/slackify-markdown/issues/25

**Comment by juliuscc** [comment]
Thanks! Very thorough! 😅 

This looks great 👍

**Comment by ahermant** [comment]
Thanks for the merge ! 👍
Would it be possible to tag the new release ?

**Comment by juliuscc** [comment]
Actually, CircleCI had disruptions yesterday so our CD didn't work. I will retry it now and let's hope it get's released 👍

**Comment by stelescuraul** [comment]
Can we try to release this again ?

**Pull request merged**
