### PR TITLE
feat: add option to specify slack icon

### PR DESCRIPTION
**Pull request by yoshitakahashi**

### CODE REVIEW

**Comment by juliuscc** [comment]
This looks great! Does it only work if you use a `SLACK_TOKEN`?

**Comment by yoshitakahashi** [comment]
my team only use webhook, and we were still able to update the icon :)

**Comment by yoshitakahashi** [comment]
I think i misunderstood your question. I haven't tested myself but I believe it works with slack token as well. https://api.slack.com/methods/chat.postMessage

**Review by juliuscc — APPROVED** [review]
Nice! This looks good to me!

**Pull request merged**
